### ISSUE TITLE
Schematic PDF is hard to read and cannot be searched.

### ISSUE THREAD

**Issue by herbertp** [AlphamaxMedia/netv2-mainboard#1]
For developers working with open hardware good schematics are essential.

Currently the schematic design for the NeTV2 is only available as proprietary Altium files or as PDF of relatively bad quality (basically low resolution images packed into a PDF) and certain parts can't even be deciphered by guessing.

It would be really nice to have a proper (scalable) PDF which uses searchable text elements.
A quick google search shows that Altium can output proper PDFs and there are also additional tools available to help with the process.

Many thanks in advance,
Herbert

**Comment by bunnie** [comment]
That's strange -- I'm able to search the schematic PDF and view it just fine in arbitrary resolution using Acrobat reader. Are you looking at this file:

https://github.com/AlphamaxMedia/netv2-mainboard/blob/master/netv2mvp-pvt1.pdf

Note that when you view on github they turn it into an image that is not searchable and it sort of matches the situation you mention. You need to download it to your local machine and view it with a local viewer for all the features to work.

![4-11-2019 14-22-50](https://user-images.githubusercontent.com/1168375/55935121-5dffac80-5c65-11e9-97ca-51c36d801fdf.png)

Above is a screenshot of how the schematics look to me in my PDF browser.

**Comment by herbertp** [comment]
You are completely right, the PDF is perfectly fine just the GitHub Viewer messes it up pretty good.
Sorry for the noise, will complain there ... thanks for pointing that out!

All the best and keep up the good work,
Herbert
